### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by em-oaken** [benrutter/hop#5]
Hi,
I like this project and I'd like to contribute.
Do you take PR? Are there specific features in the pipeline for implementation?
Thanks,
Em

**Comment by benrutter** [comment]
Hey! I haven't done much on this project for a while, but i'd definitely accept a pull request if you have a feature or bugfix you wanted to contribute. I don't have a feature pipeline or anything, but if you wanted to pick up something specific, the implementation of using arrow keys to navigate seems kinda unreliable across different operationing systems, so if you can find a better way to handle that function then that would be immense!
